### ISSUE TITLE
Add extensions to chromatichq/php-apache-node image?

### ISSUE THREAD

**Issue by mmatsoo** [ChromaticHQ/docker-images#83]
## Description
There are (at least) a couple of our projects that install extensions in `.tugboat/config.yml` that could be pre-installed in the Docker image being used (`chromatichq/php-apache-node:8.3`).

Namely, I have found these lines in both Cuningham's and Imprivata's `.tugboat/config.yml` files.
```yml
image: 'chromatichq/php-apache-node:8.3'
.
.
.
  commands:
    init:
      - apt-get update
      - apt-get install --yes jpegoptim pngquant libwebp-dev
     # Configure GD with WebP Support.
      - docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg
      - docker-php-ext-install gd
```

If `jpegoptim`, `pngquant` etc. were pre-installed in the image, we could get rid of them from the projects' `.tugboat/config.yml` files.
